PACKAGE := system-tools
PROGRAMS := hive lscpu lspci top tree userctl dmesg insmod lsdisk lsmod mkfat mkneufs mkpart mount sensors shutdown
SUPPORT_HELPERS := args console
include ../userspace-support/package.mk
