PACKAGE := network-tools
PROGRAMS := browse netctl netget netshell ping tcpecho svcmock svctest
EXTRA_LIBS := ../libnet/library/libnet.so.0 ../bearssl/library/libbearssl.so.0
include ../userspace-support/package.mk
