[neutrino-drivers]
version = "0.2.0"
strategy = "over_root"
description = "Complete metapackage for all Neutrino loadable hardware drivers"
depends = ["e1000e", "virtio-net", "intel-hda", "intel-uhd-gemini-lake"]
