[network-tools]
version = "2.3.0"
strategy = "over_root"
description = "Network clients and diagnostics for Neutrino"
depends = ["base-system", "bearssl", "ca-certificates", "network-services", "libnet"]
