[neutrino-live]
version = "0.1.0"
strategy = "over_root"
description = "Complete userspace installed by the Neutrino live environment"
depends = ["base-system", "bearssl", "coreutils", "neupak", "network-services", "network-tools", "system-tools", "text-tools", "console-tools", "editor-tools", "neutrino-drivers"]
